Level	  = "debug"

[Console]
SystemOut = false

[LocalFile]
SaveFile  = true
MaxSize   = 100
MaxBackups= 30
MaxAge    = 7
Compress  = false
Ignored = "rawtx,txLocal,txRemote,txBlock,messager,unknown,checkedtx,checkingtx,executingLogs,receipts,euResults"